name: API Automation Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Install Playwright browsers (required for Playwright even if only API tests)
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Run Cucumber tests with ts-node
      - name: Run Cucumber API Tests
        run: |
          npx cucumber-js --require-module ts-node/register 

      # Generate HTML report (from JSON)
      - name: Generate Cucumber HTML report
        run: |
          mkdir -p reports
          node report.js

      # Upload report as artifact
      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports
          path: reports/
